CREATE TABLE "roles" (
    "id_role" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(20) NOT NULL UNIQUE,
    "role_description" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "users" (
    "id_user" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "firstname" VARCHAR(255) NOT NULL,
    "lastname" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(60) NOT NULL,
    "phone_number" INT,
    "street_number" INT NOT NULL,
    "street" VARCHAR(255) NOT NULL,
    "city" VARCHAR(100) NOT NULL,
    "postal_code" INT(10) NOT NULL,
    "country" VARCHAR(100) NOT NULL,
    "entity_name" VARCHAR(255),
    "entity_type" VARCHAR(50),
    "entity_siret" VARCHAR(14),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "id_role" INT NOT NULL,
    FOREIGN KEY ("id_role") REFERENCES "roles"("id_role")
);

CREATE TABLE "reviews" (
    "id_review" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "content" VARCHAR(255),
    "rating" INT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "id_user" INT NOT NULL,
    FOREIGN KEY ("id_user") REFERENCES "users"("id_user")
);

CREATE TABLE "bookmarks" (
    PRIMARY KEY ("id_user", "id_campaign"),
    "id_user" INT NOT NULL,
    "id_campaign" INT NOT NULL,
    FOREIGN KEY ("id_user") REFERENCES "users"("id_user"),
    FOREIGN KEY ("id_campaign") REFERENCES "campaigns"("id_campaign")
);

CREATE TABLE "TreeSpecies" (
    "id_species" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "description" TEXT NOT NULL,
    "species_name" VARCHAR(255) NOT NULL UNIQUE,
    "co2_absorption" INT NOT NULL,
    "average_lifespan" INT NOT NULL
);

CREATE TABLE "Trees" (
    "id_tree" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "price_HT" NUMERIC(10,2),
    "quantity" INT,
    "age" INT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "id_species" INT,
    FOREIGN KEY ("id_species") REFERENCES "TreeSpecies"("id_species")
);

CREATE TABLE "campaigns" (
    "id_campaign" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "start_campaign" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "end_campaign" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "id_tree" INT,
    "id_campaign_location" INT,
    FOREIGN KEY ("id_tree") REFERENCES "Trees"("id_tree")
    FOREIGN KEY ("id_campaign_location") REFERENCES "CampaignLocations"("id_location")
);

CREATE TABLE "CampaignLocations" (
    "id_location" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name_location" VARCHAR(255) NOT NULL,
    "id_country" INT NOT NULL,
    FOREIGN KEY ("id_country") REFERENCES "country"("id_country")
);

CREATE TABLE "country" (
    "id_country" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "orders" (
    "id_order" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "total_amount" NUMERIC(10,2) NOT NULL,
    "status" VARCHAR(50) NOT NULL,
    "order_number" VARCHAR(50) NOT NULL UNIQUE,
    "id_user" INT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("id_user") REFERENCES "users"("id_user")
);

CREATE TABLE "OrderDetails" (
    "id_detail" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "price_HT_at_order" NUMERIC(10,2) NOT NULL,
    "quantity" INT NOT NULL,
    "total_amount" NUMERIC(10,2) NOT NULL,
    "id_order" INT NOT NULL,
    "id_tree" INT NOT NULL,
    "id_campaign" INT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("id_order") REFERENCES "orders"("id_order"),
    FOREIGN KEY ("id_tree") REFERENCES "Trees"("id_tree")
);
